import { useCallback } from 'react';
import { useLocalStorage } from '../../hooks/useLocalStorage';

export type Language = 'en' | 'es';

const translations: Record<Language, Record<string, string>> = {
    en: {
        "user_login": "Log in to find your worker",
        "user_signup": "Sign up to find your worker",
        "worker_login": "Log in to find your next job",
        "worker_signup": "Sign up to find your next job",
        "admin_login": "Admin Login",
        "admin_signup": "Admin Sign Up",
        "forgot_password": "Forgot Password.",
        "password recovery": "Password Recovery",
        "password recovery subtitle": "Enter your email or phone number to receive a recovery code.",
        "choose recovery method": "Choose how you want to recover your password",
        "choose recovery method subtitle": "Select one of the options below to receive a security code.",
        "recover via email": "Recover via Email",
        "recover via phone": "Recover via Phone Number",
        "enter email": "Enter your email address",
        "enter phone": "Enter your phone number",
        "recover_email_subtitle": "We will send a security code to your registered email address.",
        "recover_phone_subtitle": "We will send a security code to your registered phone number.",
        "change method": "Change recovery method",
        "recovery code": "Recovery Code",
        "dont_have_account": "Don't have an account?",
        "already_have_account": "Already have an account?",
        "signup": "Sign up",
        "login": "Log in",
        "create_account": "Create Account",
        "full_name": "Full Name",
        "email_address": "Email Address",
        "password": "Password",
        "confirm_password": "Confirm Password",
        "id_number": "ID Number",
        "country_code": "Country Code",
        "phone_number": "Phone Number",
        "accept_terms": "I accept the",
        "terms_and_services": "Terms and Services",
        "must_accept_terms": "You must accept the terms and services.",
        "passwords_do_not_match": "Passwords do not match.",
        "fill_all_fields": "Please fill all fields.",
        "welcome to": "Welcome to",
        "welcome to tufix": "Welcome to TUFIX",
        "auth subtitle": "Where Skill Meets Need",
        "need service": "I need a service",
        "provide service": "I want to provide a service",
        "i am admin": "I am an administrator",
        "filters": "Filters",
        "search by name": "Search by name...",
        "search for a service": "Search for a service, job type, or professional...",
        "region": "Region",
        "all regions": "All Regions",
        "date available": "Date Available",
        "price range": "Price Range",
        "min price": "Min price",
        "max price": "Max price",
        "number of reviews": "Number of Reviews",
        "min reviews": "Min reviews",
        "max reviews": "Max reviews",
        "min rating": "Minimum Rating",
        "job specialties": "Job Specialties",
        "reset filters": "Reset Filters",
        "any rating": "Any Rating",
        "find a service": "Find a Service",
        "find a professional": "Find a Professional",
        "back to categories": "Back to Categories",
        "no professionals found": "No professionals found matching your criteria.",
        "select specialty prompt": "Select a specialty above to see available professionals.",
        "job avg": "(avg/job)",
        "back to results": "Back to Results",
        "about worker": "About {name}",
        "contact": "Contact",
        "book now": "Book Now",
        "availability": "Availability",
        "service areas": "Service Areas",
        "back to profile": "Back to Profile",
        "book service with": "Book Service with {name}",
        "booking subtitle": "You are booking a {service}. Please select a date and time.",
        "select date": "1. Select a Date",
        "select time": "2. Select a Time",
        "please select date": "Please select a date to see available time slots.",
        "no slots available": "No time slots available for this date.",
        "describe job": "3. Describe the Job",
        "job description placeholder": "Please provide as much detail as possible about the {service} work you need done.",
        "submit request": "Submit Request",
        "cancel": "Cancel",
        "select rating alert": "Please select a star rating before submitting.",
        "leave comment alert": "Please leave a comment before submitting.",
        "leave review title": "Leave a Review",
        "review for worker subtitle": "How was your experience with {name} for the {service} job?",
        "your rating": "Your Rating",
        "your review": "Your Review",
        "review placeholder worker": "Share your experience with {name}. Was the work well done? Were they on time?",
        "submit review": "Submit Review",
        "welcome back": "Welcome back, {name}!",
        "incoming jobs": "Incoming Jobs",
        "no job requests": "You have no new jobs at this time.",
        "available this day": "Available this day",
        "potentially unavailable": "Potentially unavailable",
        "view details": "View Details",
        "raise dispute": "Raise a Dispute",
        "view dispute": "View Dispute",
        "client rating": "Client Rating",
        "review for user subtitle": "How was your experience working with {name} for the {service} job?",
        "review placeholder user": "Share your experience with {name}. Were they clear with instructions? Was the payment process smooth?",
        "service category": "Service Category",
        "category": "Category",
        "specialty": "Specialty",
        "avg job cost": "Average Job Cost",
        "type region enter": "Type a region and press Enter",
        "remove region": "Remove {region}",
        "custom availability calendar": "Custom Availability Overrides",
        "custom availability desc": "Click a date to add a custom schedule or mark yourself as unavailable for a specific day.",
        "edit availability": "Edit Availability",
        "current overrides": "Current Overrides",
        "no overrides set": "No overrides have been set.",
        "job description": "Job Description",
        "requested for": "Requested for",
        "client information": "Client Information",
        "view profile": "View Profile",
        "contact client": "Contact Client",
        "accept job": "Accept Job",
        "decline": "Decline",
        "decline reason prompt": "Please provide a brief reason for declining.",
        "create invoice": "Create Invoice",
        "start job": "Start Job",
        "finish request confirmation": "Finish & Request Confirmation",
        "review client": "Review Client",
        "job is complete": "Job is complete.",
        "my jobs": "My Jobs",
        "requested on": "Requested on {date}",
        "pay invoice": "Pay Invoice",
        "confirm completion": "Confirm Completion",
        "leave review": "Leave Review",
        "cancellation reason prompt": "Please provide a reason for cancellation.",
        "cancel request": "Cancel Request",
        "no jobs found": "You haven't requested any jobs yet.",
        "invoice for": "Invoice for {service} job for {name}",
        "add line item": "+ Add Line Item",
        "subtotal": "Subtotal",
        "platform fee": "Platform Fee (10%)",
        "total amount": "Total Amount",
        "complete job send invoice": "Send Invoice",
        "raise dispute title": "Raise a Dispute",
        "dispute for job": "Regarding your {service} job on {date}",
        "reason for dispute": "Reason for Dispute",
        "dispute reason subtitle": "Please explain the issue in detail. An administrator will review your case.",
        "dispute reason placeholder": "e.g., The work was not completed to the agreed standard, there was a disagreement about the price, etc.",
        "provide dispute reason alert": "Please provide a reason for the dispute.",
        "submit dispute": "Submit Dispute",
        "back to jobs": "Back to My Jobs",
        "dispute details": "Dispute Details",
        "dispute status open": "Open",
        "dispute status under review": "Under Review",
        "dispute status resolved": "Resolved",
        "original claim": "Original Claim",
        "raised on": "Raised on {date}",
        "mediation history": "Mediation History",
        "no admin comment": "An administrator has not yet commented on this dispute.",
        "final resolution details": "Final Resolution",
        "resolved on": "Resolved on {date}",
        "my conversations": "My Conversations",
        "no conversations": "You have no conversations.",
        "you prefix": "You: ",
        "viewing as admin": "Viewing conversation as Admin",
        "weekly": "Weekly",
        "monthly": "Monthly",
        "yearly": "Yearly",
        "total earnings all time": "Total Earnings (All Time)",
        "jobs completed all time": "Jobs Completed (All Time)",
        "average job value": "Average Job Value",
        "my earnings": "My Earnings",
        "period earnings": "{period} Earnings",
        "no earnings data": "No earnings data available for this period.",
        "job history": "Job History",
        "client": "Client",
        "service": "Service",
        "date completed": "Date Completed",
        "amount earned": "Amount Earned",
        "no completed jobs": "You have no completed jobs yet.",
        "cancelled": "Cancelled",
        "admin dashboard": "Admin Dashboard",
        "edit terms and services": "Edit Terms & Services",
        "total clients": "Total Clients",
        "total workers": "Total Workers",
        "jobs completed": "Jobs Completed",
        "open disputes": "Open Disputes",
        "clients": "Clients",
        "providers": "Providers",
        "transactions": "Transactions",
        "disputes": "Disputes",
        "support": "Support",
        "support requests": "Support Requests",
        "no support requests": "No open support requests.",
        "client management": "Client Management",
        "toggle filters": "Toggle Filters",
        "name or email": "Name or Email",
        "min jobs": "Min Jobs",
        "max jobs": "Max Jobs",
        "joined between": "Joined Between",
        "last login between": "Last Login Between",
        "jobs": "Jobs",
        "workers": "Workers",
        "joined": "Joined",
        "provider management": "Provider Management",
        "all services": "All Services",
        "rating label": "Rating:",
        "min": "Min",
        "max": "Max",
        "jobs label": "Jobs:",
        "earnings label": "Earnings:",
        "provider": "Provider",
        "jobs done": "Jobs Done",
        "rating": "Rating",
        "total platform revenue": "Total Platform Revenue",
        "total volume": "Total Volume",
        "paid out to providers": "Paid out to Providers",
        "currently in escrow": "Currently in Escrow",
        "search by name email id": "Search by name, email, or ID...",
        "all statuses": "All Statuses",
        "held in escrow": "Held in Escrow",
        "paid out": "Paid Out",
        "paid between": "Paid Between",
        "amount label": "Amount:",
        "no matching transactions": "No transactions match the current filters.",
        "transaction id": "Transaction ID",
        "date paid": "Date Paid",
        "fee": "Fee",
        "dispute management": "Dispute Management",
        "all": "All",
        "job details": "Job Details",
        "parties involved": "Parties Involved",
        "date raised": "Date Raised",
        "job id label": "Job ID:",
        "client abbr label": "C:",
        "worker abbr label": "W:",
        "raised by label": "Raised by:",
        "user role label": "(Client)",
        "worker role label": "(Provider)",
        "no matching disputes": "No disputes match the current filters.",
        "back to admin dashboard": "Back to Admin Dashboard",
        "joined label": "Joined:",
        "last seen label": "Last Seen:",
        "id number label": "ID Number:",
        "no client jobs": "This client has not requested any jobs.",
        "conversations": "Conversations",
        "view messages": "View Messages",
        "no conversations found": "No conversations found.",
        "no provider jobs": "This provider has not completed any jobs.",
        "dispute resolution": "Dispute Resolution",
        "dispute id label": "Dispute ID:",
        "job summary": "Job Summary",
        "service label": "Service:",
        "date label": "Date:",
        "amount in escrow": "Amount in Escrow:",
        "initial claim": "Initial Claim",
        "raised by": "Raised by",
        "mediation chat": "Mediation Chat",
        "no mediation messages": "There are no messages in this mediation chat yet.",
        "type mediation message": "Type your message to both parties...",
        "dispute resolved": "Dispute Resolved",
        "resolution label": "Resolution:",
        "fund action label": "Fund Action:",
        "resolve dispute": "Resolve Dispute",
        "final resolution": "Final Resolution",
        "select fund action": "1. Select Fund Action",
        "release full to worker": "Release full payment to Worker",
        "refund full to client": "Refund full amount to Client",
        "refund partial to client": "Refund a partial amount to Client",
        "refund amount": "Refund Amount",
        "final resolution summary": "2. Final Resolution Summary",
        "summarize resolution placeholder": "Summarize the final decision and the reason for the action taken. This will be visible to both parties.",
        "confirm and resolve": "Confirm and Resolve",
        "terms edit subtitle": "Make changes to the Terms and Services content. The new version will be shown to all new users upon signing up.",
        "confirm release title": "Confirm Job Completion & Release Payment",
        "confirm release body": "By confirming, you agree that the job is complete and authorize the release of the escrowed payment of {amount}. This action is final.",
        "confirm release action": "Confirm & Release",
        "invoice": "Invoice",
        "payment held": "Payment Held",
        // FIX: Removed duplicate "paid_out" key which caused a compilation error.
        "view receipt": "View Receipt",
        "payment secured": "Payment secured. Funds will be released upon job completion.",
        "pay now": "Pay Now",
        "waiting for payment": "Waiting for client payment.",
        "job progress": "Job Progress",
        "job created": "Job Created",
        "invoice sent": "Invoice Sent",
        "payment made": "Payment Made",
        "job started": "Job Started",
        "job finished by worker": "Job Finished by Worker",
        "payment released": "Payment Released",
        "scan qr to pay": "Scan QR Code to Pay",
        "scan qr instruction": "Scan this code with your banking app to pay {amount}.",
        "confirm payment transfer": "I Have Completed the Transfer",
        "payment information": "Payment Information (BOB)",
        "bank account number": "Bank Account Number",
        "payout info subtitle": "Please provide your Bolivian bank account number for payouts.",
        "tufix_ai_support": "TUFIX AI Support",
        "ai_support_welcome": "Hello! I am TUFIX AI Support. How can I help you today?",
        "ai_support_error": "I'm sorry, an error occurred. Please try again.",
        "ask_placeholder": "Type your question here...",
        "close_ai_support_chat": "Close AI Support Chat",
        "open_ai_support_chat": "Open AI Support Chat",
        // FIX: Added missing translation keys.
        "back to job details": "Back to Job Details",
        "reviews from providers": "Reviews from Providers",
        "this client has no reviews": "This client has no reviews from providers yet.",
        "identity verification": "Identity Verification",
        "identity verification subtitle": "For security, we need to verify your identity before you can offer services.",
        "upload id photo": "Upload ID Photo",
        "click to upload id": "Click to upload your ID (front side)",
        "next step selfie": "Next: Take a Selfie",
        "next step phone": "Next: Verify Phone",
        "take a selfie": "Take a Selfie",
        "take photo": "Take Photo",
        "retake": "Retake",
        "submit verification": "Submit Verification",
        "verification submitted": "Verification Submitted",
        "verification submitted subtitle": "This usually takes about 1 to 2 hours to process.",
        "back to home": "Back to Home",
        "verify_phone": "Verify Phone Number",
        "verify_phone_subtitle": "Please verify your phone number to continue.",
        "verification_code": "Verification Code",
        "verify": "Verify",
        "verifications": "Verifications",
        "pending verifications": "Pending Verifications",
        "no pending verifications": "There are no pending verifications.",
        "back to verifications": "Back to Verifications",
        "id photo": "ID Photo",
        "selfie photo": "Selfie Photo",
        "approve": "Approve",
        "confirm decline": "Confirm Decline",
        "download csv": "Download CSV",
        "submitted": "Submitted:",
        "Phone Repair": "Phone Repair",
        "Screen Replacement": "Screen Replacement",
        "Battery Replacement": "Battery Replacement",
        "Charging Port Repair": "Charging Port Repair",
        "Water Damage Repair": "Water Damage Repair",
        "Software Troubleshooting": "Software Troubleshooting",
        "Data Recovery": "Data Recovery",
        "job requests": "Jobs",
        "Monday": "Monday",
        "Tuesday": "Tuesday",
        "Wednesday": "Wednesday",
        "Thursday": "Thursday",
        "Friday": "Friday",
        "Saturday": "Saturday",
        "Sunday": "Sunday",
        "Mon": "Mon",
        "Tue": "Tue",
        "Wed": "Wed",
        "Thu": "Thu",
        "Fri": "Fri",
        "Sat": "Sat",
        "Sun": "Sun",
        "danger zone": "Danger Zone",
        "clear all data description": "This will permanently delete all users, workers, jobs, messages, and notifications from the database. This action cannot be undone.",
        "clear all data": "Clear All Data",
        "confirm clear all data": "Confirm Clear All Data",
        "clear all data warning": "Are you sure you want to delete everything? This will reset the entire application database.",
        "yes clear all": "Yes, Clear Everything",
        "secure payment": "Secure Payment",
        "you are paying a total of": "You are paying a total of",
        "name on card": "Name on Card",
        "card number": "Card Number",
        "expiry date": "Expiry Date",
        "cvc": "CVC",
        "please fill in all card details": "Please fill in all card details.",
        "please enter a valid 16-digit card number": "Please enter a valid 16-digit card number.",
        "please use mm/yy format for expiry date": "Please use MM/YY format for expiry date.",
        "please enter a valid cvc": "Please enter a valid CVC.",
        "pay": "Pay",
        "payment successful": "Payment Successful",
        "a receipt for your transaction": "A receipt for your transaction",
        "paid by": "Paid by",
        "paid to": "Paid to",
        "summary": "Summary",
        "total paid": "Total Paid",
        "close": "Close",
        "all items must have a description and an amount greater than zero": "All items must have a description and an amount greater than zero.",
        "you must add at least one item to the invoice": "You must add at least one item to the invoice.",
        "item description placeholder": "Item Description (e.g., Labor, Materials)",
        "amount": "Amount",
        "please provide a final resolution summary": "Please provide a final resolution summary.",
        "partial refund must be greater than 0 and less than total": "Partial refund must be greater than 0 and less than total of {total}.",
        "please complete all verification steps": "Please complete all verification steps.",
        "please provide a reason for declining": "Please provide a reason for declining.",
        "please select a date time and provide a description": "Please select a date, time and provide a description.",
        "your tufix recovery code is": "Your TUFIX recovery code is: {code}",
        "account has been approved": "Account for {name} has been approved.",
        "account has been declined": "Account for {name} has been declined.",
        "please log in as a user to book a service": "Please log in as a user to book a service.",
        "booking request submitted successfully": "Booking request submitted successfully!",
        "cannot release payment while dispute is active": "Cannot release payment while dispute is active. Please wait for an administrator to resolve the dispute.",
        "error invoice is not in a payable state": "Error: Invoice is not in a payable state.",
        "job confirmed and payment released": "Job confirmed and payment released! The service provider has been paid.",
        "profile updated successfully": "Profile updated successfully!",
        "invoice sent you can now start the job": "Invoice sent! You can now start the job.",
        "payment successful funds held securely": "Payment successful! Funds are held securely until you approve the payment.",
        "error could not find all related records for this dispute": "Error: Could not find all related records for this dispute.",
        "dispute has been resolved and funds have been processed": "The dispute has been resolved and funds have been processed.",
        "terms and services updated successfully": "Terms and Services updated successfully!",
        "you have been connected to a live support agent": "You have been connected to a live support agent. You can find the chat in your messages.",
        "select_rating_alert": "Please select a rating.",
        "leave_comment_alert": "Please leave a comment.",
        "admin accounts cannot be created": "Admin accounts cannot be created from the sign-up form.",
        "service provider": "Service Provider",
        "administrator": "Administrator",
        "find the perfect professional": "Find the perfect professional",
        "grow your business": "Grow your business",
        "manage the platform": "Manage the platform",
        "connect with skilled workers": "Connect with skilled workers in your area for any job.",
        "find clients and manage jobs": "Find clients and manage jobs in one place.",
        "oversee users workers and platform": "Oversee users, workers, and platform activity.",
        "ai support welcome": "Hi! I'm your TUFIX AI Assistant. How can I help you understand our platform?",
        "ai support error": "I'm sorry, something went wrong. Please try again.",
        "tufix ai support": "TUFIX AI Support",
        "ask placeholder": "Ask something...",
        "language": "Language",
        "close ai support chat": "Close AI support chat",
        "open ai support chat": "Open AI support chat",
        "all items must have description and amount": "All items must have a description and a valid amount greater than zero.",
        "must add at least one item": "You must add at least one item to the invoice.",
        "for client": "For:",
        "item description example": "Item description (e.g. Labor)",
        "total": "Total:",
        "send invoice": "Send Invoice",
        "recovery code sent": "A recovery code has been sent to you. Please enter it below.",
        "edit your profile": "Edit your profile",
        "change photo": "Change photo",
        "location": "Location",
        "about me bio": "About me (Bio)",
        "weekly availability": "Weekly availability",
        "start_time": "Start time",
        "end_time": "End time",
        "save changes": "Save changes",
        "new status": "New",
        "accepted status": "Accepted",
        "completed status": "Completed",
        "disputed status": "Disputed",
        "no specific services listed": "No specific services listed in this category yet.",
        "invoice not found": "Invoice not found.",
        "in conversation with": "In conversation with {name}",
        "image selected ready to send": "Image selected. Ready to send.",
        "send image": "Send Image",
        "english": "English (EN)",
        "spanish": "Spanish (ES)",
        "regular": "Regular",
        "custom": "Custom",
        "day off": "Day Off",
        "available": "Available",
        "unavailable": "Unavailable",
        "no worker data": "No worker data.",
        "price not available": "Price not available",
        "no reviews yet": "This professional has no reviews yet.",
        "supported formats": "JPG, PNG or PDF",
        "camera access error": "Could not access camera. Please check permissions and try again.",
        "failed to send verification code": "Failed to send verification code",
        "sms error": "Could not send SMS: {error}. Please check your Twilio configuration.",
        "invalid verification code": "Invalid verification code. Please try again.",
        "worker verification": "Worker Verification",
        "worker verification description": "Review the submitted documents to approve or decline the new service provider.",
        "provider details": "Provider Details",
        "id document": "ID Document",
        "no id photo submitted": "No ID photo submitted.",
        "selfie": "Selfie",
        "no selfie submitted": "No selfie submitted.",
        "decline application": "Decline Application",
        "decline application description": "Please provide a clear reason for declining this application. This reason will be shared with the applicant.",
        "decline reason placeholder": "e.g., ID photo is unclear, selfie does not match ID...",
        "id prefix": "ID:",
        "fee prefix": "Fee:",
        "held": "Held",
        "released": "Released",
        "not available": "Not Available",
        "verify_phone_description": "Please verify your phone number, we have sent you a 4 digit code to",
        "not_found": "Not Found"
    },
    es: {
        "user_login": "Inicia sesión para encontrar a tu trabajador",
        "user_signup": "Regístrate para encontrar a tu trabajador",
        "worker_login": "Inicia sesión para encontrar tu próximo trabajo",
        "worker_signup": "Regístrate para encontrar tu próximo trabajo",
        "admin_login": "Inicio de sesión de Administrador",
        "admin_signup": "Registro de Administrador",
        "forgot_password": "Olvidé mi contraseña.",
        "password recovery": "Recuperación de Contraseña",
        "password recovery subtitle": "Ingrese su correo electrónico o número de teléfono para recibir un código de recuperación.",
        "choose recovery method": "Elija cómo desea recuperar su contraseña",
        "choose recovery method subtitle": "Seleccione una de las opciones a continuación para recibir un código de seguridad.",
        "recover via email": "Recuperar por Correo Electrónico",
        "recover via phone": "Recuperar por Número de Teléfono",
        "enter email": "Ingrese su correo electrónico",
        "enter phone": "Ingrese su número de teléfono",
        "recover_email_subtitle": "Enviaremos un código de seguridad a su dirección de correo electrónico registrada.",
        "recover_phone_subtitle": "Enviaremos un código de seguridad a su número de teléfono registrado.",
        "change method": "Cambiar método de recuperación",
        "recovery code": "Código de Recuperación",
        "dont_have_account": "¿No tienes una cuenta?",
        "already_have_account": "¿Ya tienes una cuenta?",
        "signup": "Regístrate",
        "login": "Inicia sesión",
        "create_account": "Crear Cuenta",
        "full_name": "Nombre Completo",
        "email_address": "Correo Electrónico",
        "password": "Contraseña",
        "confirm_password": "Confirmar Contraseña",
        "id_number": "Número de Identificación",
        "country_code": "Código de País",
        "phone_number": "Número de Teléfono",
        "accept_terms": "Acepto los",
        "terms_and_services": "Términos y Servicios",
        "must_accept_terms": "Debes aceptar los términos y servicios.",
        "passwords_do_not_match": "Las contraseñas no coinciden.",
        "fill_all_fields": "Por favor, completa todos los campos.",
        "welcome to": "Bienvenido a",
        "welcome to tufix": "Bienvenido a TUFIX",
        "auth subtitle": "Donde la Habilidad se Une a la Necesidad",
        "need service": "Necesito un servicio",
        "provide service": "Quiero ofrecer un servicio",
        "i am admin": "Soy administrador",
        "filters": "Filtros",
        "search by name": "Buscar por nombre...",
        "search for a service": "Buscar un servicio, tipo de trabajo o profesional...",
        "region": "Región",
        "all regions": "Todas las Regiones",
        "date available": "Fecha Disponible",
        "price range": "Rango de Precios",
        "min price": "Precio mín.",
        "max price": "Precio máx.",
        "number of reviews": "Número de Reseñas",
        "min reviews": "Mín. reseñas",
        "max reviews": "Máx. reseñas",
        "min rating": "Calificación Mínima",
        "job specialties": "Especialidades de Trabajo",
        "reset filters": "Limpiar Filtros",
        "any rating": "Cualquier Calificación",
        "find a service": "Encuentra un Servicio",
        "find a professional": "Encuentra un Profesional",
        "back to categories": "Volver a Categorías",
        "no professionals found": "No se encontraron profesionales con tus criterios.",
        "select specialty prompt": "Selecciona una especialidad para ver los profesionales disponibles.",
        "job avg": "(prom/trabajo)",
        "back to results": "Volver a Resultados",
        "about worker": "Sobre {name}",
        "contact": "Contactar",
        "book now": "Reservar Ahora",
        "availability": "Disponibilidad",
        "service areas": "Áreas de Servicio",
        "back to profile": "Volver al Perfil",
        "book service with": "Reservar Servicio con {name}",
        "booking subtitle": "Estás reservando un servicio de {service}. Por favor, selecciona una fecha y hora.",
        "select date": "1. Selecciona una Fecha",
        "select time": "2. Selecciona una Hora",
        "please select date": "Por favor, selecciona una fecha para ver los horarios disponibles.",
        "no slots available": "No hay horarios disponibles para esta fecha.",
        "describe job": "3. Describe el Trabajo",
        "job description placeholder": "Por favor, proporciona tantos detalles como sea posible sobre el trabajo de {service} que necesitas.",
        "submit request": "Enviar Solicitud",
        "cancel": "Cancelar",
        "select rating alert": "Por favor, selecciona una calificación de estrellas antes de enviar.",
        "leave comment alert": "Por favor, deja un comentario antes de enviar.",
        "leave review title": "Dejar una Reseña",
        "review for worker subtitle": "¿Cómo fue tu experiencia con {name} para el trabajo de {service}?",
        "your rating": "Tu Calificación",
        "your review": "Tu Reseña",
        "review placeholder worker": "Comparte tu experiencia con {name}. ¿El trabajo estuvo bien hecho? ¿Llegó a tiempo?",
        "submit review": "Enviar Reseña",
        "reviews": "Reseñas",
        "welcome back": "¡Bienvenido de vuelta, {name}!",
        "incoming jobs": "Trabajos Entrantes",
        "no job requests": "No tienes nuevos trabajos en este momento.",
        "available this day": "Disponible este día",
        "potentially unavailable": "Potencialmente no disponible",
        "view details": "Ver Detalles",
        "raise dispute": "Iniciar una Disputa",
        "view dispute": "Ver Disputa",
        "client rating": "Calificación del Cliente",
        "review for user subtitle": "¿Cómo fue tu experiencia trabajando con {name} para el trabajo de {service}?",
        "review placeholder user": "Comparte tu experiencia con {name}. ¿Fueron claras sus instrucciones? ¿El proceso de pago fue fácil?",
        "service category": "Categoría de Servicio",
        "category": "Categoría",
        "specialty": "Especialidad",
        "avg job cost": "Costo Promedio por Trabajo",
        "type region enter": "Escribe una región y presiona Enter",
        "remove region": "Quitar {region}",
        "custom availability calendar": "Anulaciones de Disponibilidad Personalizada",
        "custom availability desc": "Haz clic en una fecha para añadir un horario personalizado o marcarte como no disponible para un día específico.",
        "edit availability": "Editar Disponibilidad",
        "current overrides": "Anulaciones Actuales",
        "no overrides set": "No se han establecido anulaciones.",
        "job description": "Descripción del Trabajo",
        "requested for": "Solicitado para",
        "client information": "Información del Cliente",
        "view profile": "Ver Perfil",
        "contact client": "Contactar al Cliente",
        "accept job": "Aceptar Trabajo",
        "decline": "Rechazar",
        "decline reason prompt": "Por favor, proporciona una breve razón para el rechazo.",
        "create invoice": "Crear Factura",
        "start job": "Empezar Trabajo",
        "finish request confirmation": "Finalizar y Solicitar Confirmación",
        "review client": "Evaluar al Cliente",
        "job is complete": "El trabajo está completo.",
        "my jobs": "Mis Trabajos",
        "requested on": "Solicitado el {date}",
        "pay invoice": "Pagar Factura",
        "confirm completion": "Confirmar Finalización",
        "leave review": "Dejar Reseña",
        "cancellation reason prompt": "Por favor, proporciona una razón para la cancelación.",
        "cancel request": "Cancelar Solicitud",
        "no jobs found": "Aún no has solicitado ningún trabajo.",
        "invoice for": "Factura por trabajo de {service} para {name}",
        "add line item": "+ Añadir Línea",
        "subtotal": "Subtotal",
        "platform fee": "Comisión de Plataforma (10%)",
        "total amount": "Monto Total",
        "complete job send invoice": "Enviar Factura",
        "raise dispute title": "Iniciar una Disputa",
        "dispute for job": "Sobre tu trabajo de {service} el {date}",
        "reason for dispute": "Razón de la Disputa",
        "dispute reason subtitle": "Por favor, explica el problema en detalle. Un administrador revisará tu caso.",
        "dispute reason placeholder": "Ej: El trabajo no se completó según lo acordado, hubo un desacuerdo sobre el precio, etc.",
        "provide dispute reason alert": "Por favor, proporciona una razón para la disputa.",
        "submit dispute": "Enviar Disputa",
        "back to jobs": "Volver a Mis Trabajos",
        "dispute details": "Detalles de la Disputa",
        "dispute status open": "Abierta",
        "dispute status under review": "En Revisión",
        "dispute status resolved": "Resuelta",
        "original claim": "Reclamo Original",
        "raised on": "Iniciada el {date}",
        "mediation history": "Historial de Mediación",
        "no admin comment": "Un administrador aún no ha comentado en esta disputa.",
        "final resolution details": "Resolución Final",
        "resolved on": "Resuelta el {date}",
        "my conversations": "Mis Conversaciones",
        "no conversations": "No tienes conversaciones.",
        "you prefix": "Tú: ",
        "viewing as admin": "Viendo conversación como Administrador",
        "weekly": "Semanal",
        "monthly": "Mensual",
        "yearly": "Anual",
        "total earnings all time": "Ganancias Totales (Histórico)",
        "jobs completed all time": "Trabajos Completados (Histórico)",
        "average job value": "Valor Promedio por Trabajo",
        "my earnings": "Mis Ganancias",
        "period earnings": "Ganancias del Período ({period})",
        "no earnings data": "No hay datos de ganancias para este período.",
        "job history": "Historial de Trabajos",
        "client": "Cliente",
        "service": "Servicio",
        "date completed": "Fecha de Finalización",
        "amount earned": "Monto Ganado",
        "no completed jobs": "Aún no tienes trabajos completados.",
        "cancelled": "Cancelado",
        "admin dashboard": "Panel de Administrador",
        "edit terms and services": "Editar Términos y Servicios",
        "total clients": "Total de Clientes",
        "total workers": "Total de Proveedores",
        "jobs completed": "Trabajos Completados",
        "open disputes": "Disputas Abiertas",
        "clients": "Clientes",
        "providers": "Proveedores",
        "transactions": "Transacciones",
        "disputes": "Disputas",
        "support": "Soporte",
        "support requests": "Solicitudes de Soporte",
        "no support requests": "No hay solicitudes de soporte abiertas.",
        "client management": "Gestión de Clientes",
        "toggle filters": "Mostrar/Ocultar Filtros",
        "name or email": "Nombre o Correo",
        "min jobs": "Mín. Trabajos",
        "max jobs": "Máx. Trabajos",
        "joined between": "Se unió entre",
        "last login between": "Última sesión entre",
        "jobs": "Trabajos",
        "workers": "Trabajadores",
        "joined": "Se unió",
        "provider management": "Gestión de Proveedores",
        "all services": "Todos los servicios",
        "rating label": "Calificación:",
        "min": "Mín",
        "max": "Máx",
        "jobs label": "Trabajos:",
        "earnings label": "Ganancias:",
        "provider": "Proveedor",
        "jobs done": "Trabajos Hechos",
        "rating": "Calificación",
        "total platform revenue": "Ingresos Totales de la Plataforma",
        "total volume": "Volumen Total",
        "paid out to providers": "Pagado a Proveedores",
        "currently in escrow": "Actualmente en Depósito",
        "search by name email id": "Buscar por nombre, correo o ID...",
        "all statuses": "Todos los estados",
        "held in escrow": "En Depósito",
        "paid out": "Pagado",
        "paid between": "Pagado entre",
        "amount label": "Monto:",
        "no matching transactions": "No hay transacciones que coincidan con los filtros actuales.",
        "transaction id": "ID Transacción",
        "date paid": "Fecha de Pago",
        "fee": "Comisión",
        "dispute management": "Gestión de Disputas",
        "all": "Todas",
        "job details": "Detalles del Trabajo",
        "parties involved": "Partes Involucradas",
        "date raised": "Fecha de Inicio",
        "job id label": "ID Trabajo:",
        "client abbr label": "C:",
        "worker abbr label": "P:",
        "raised by label": "Iniciada por:",
        "user role label": "(Cliente)",
        "worker role label": "(Proveedor)",
        "no matching disputes": "No hay disputas que coincidan con los filtros actuales.",
        "back to admin dashboard": "Volver al Panel de Admin",
        "joined label": "Se unió:",
        "last seen label": "Última vez:",
        "id number label": "Nro. ID:",
        "no client jobs": "Este cliente no ha solicitado ningún trabajo.",
        "conversations": "Conversaciones",
        "view messages": "Ver Mensajes",
        "no conversations found": "No se encontraron conversaciones.",
        "no provider jobs": "Este proveedor no ha completado ningún trabajo.",
        "dispute resolution": "Resolución de Disputa",
        "dispute id label": "ID Disputa:",
        "job summary": "Resumen del Trabajo",
        "service label": "Servicio:",
        "date label": "Fecha:",
        "amount in escrow": "Monto en Depósito:",
        "initial claim": "Reclamo Inicial",
        "raised by": "Iniciado por",
        "mediation chat": "Chat de Mediación",
        "no mediation messages": "Aún no hay mensajes en este chat de mediación.",
        "type mediation message": "Escribe tu mensaje a ambas partes...",
        "dispute resolved": "Disputa Resuelta",
        "resolution label": "Resolución:",
        "fund action label": "Acción de Fondos:",
        "resolve dispute": "Resolver Disputa",
        "final resolution": "Resolución Final",
        "select fund action": "1. Seleccionar Acción de Fondos",
        "release full to worker": "Liberar pago completo al Proveedor",
        "refund full to client": "Reembolsar monto total al Cliente",
        "refund partial to client": "Reembolsar monto parcial al Cliente",
        "refund amount": "Monto a Reembolsar",
        "final resolution summary": "2. Resumen de Resolución Final",
        "summarize resolution placeholder": "Resume la decisión final y la razón de la acción tomada. Esto será visible para ambas partes.",
        "confirm and resolve": "Confirmar y Resolver",
        "terms edit subtitle": "Realiza cambios al contenido de los Términos y Servicios. La nueva versión se mostrará a todos los nuevos usuarios al registrarse.",
        "confirm release title": "Confirmar Finalización y Liberar Pago",
        "confirm release body": "Al confirmar, aceptas que el trabajo está completo y autorizas la liberación del pago en depósito de {amount}. Esta acción es final.",
        "confirm release action": "Confirmar y Liberar",
        "invoice": "Factura",
        "payment held": "Pago Retenido",
        // FIX: Removed duplicate "paid_out" key which caused a compilation error.
        "view receipt": "Ver Recibo",
        "payment secured": "Pago asegurado. Los fondos se liberarán al completar el trabajo.",
        "pay now": "Pagar Ahora",
        "waiting for payment": "Esperando pago del cliente.",
        "job progress": "Progreso del Trabajo",
        "job created": "Trabajo Creado",
        "invoice sent": "Factura Enviada",
        "payment made": "Pago Realizado",
        "job started": "Trabajo Iniciado",
        "job finished by worker": "Trabajo Finalizado por Proveedor",
        "payment released": "Pago Liberado",
        "scan qr to pay": "Escanear QR para Pagar",
        "scan qr instruction": "Escanea este código con tu app bancaria para pagar {amount}.",
        "confirm payment transfer": "He Completado la Transferencia",
        "payment information": "Información de Pago (BOB)",
        "bank account number": "Número de Cuenta Bancaria",
        "payout info subtitle": "Por favor, proporciona tu número de cuenta bancaria en Bolivia para recibir los pagos.",
        "back to job details": "Volver a Detalles del Trabajo",
        "reviews from providers": "Reseñas de Proveedores",
        "this client has no reviews": "Este cliente aún no tiene reseñas de proveedores.",
        "identity verification": "Verificación de Identidad",
        "identity verification subtitle": "Por seguridad, necesitamos verificar tu identidad antes de que puedas ofrecer servicios.",
        "upload id photo": "Subir Foto de ID",
        "click to upload id": "Haz clic para subir tu ID (lado frontal)",
        "next step selfie": "Siguiente: Tomar una Selfie",
        "next step phone": "Siguiente: Verificar Teléfono",
        "take a selfie": "Tomar una Selfie",
        "take photo": "Tomar Foto",
        "retake": "Tomar de Nuevo",
        "submit verification": "Enviar Verificación",
        "verification submitted": "Verificación Enviada",
        "verification submitted subtitle": "Esto suele tardar entre 1 y 2 horas en procesarse.",
        "back to home": "Volver al Inicio",
        "verify_phone": "Verificar Número de Teléfono",
        "verify_phone_subtitle": "Por favor, verifique su número de teléfono para continuar.",
        "verification_code": "Código de Verificación",
        "verify": "Verificar",
        "verifications": "Verificaciones",
        "pending verifications": "Verificaciones Pendientes",
        "no pending verifications": "No hay verificaciones pendientes.",
        "back to verifications": "Volver a Verificaciones",
        "id photo": "Foto de ID",
        "selfie photo": "Foto Selfie",
        "approve": "Aprobar",
        "confirm decline": "Confirmar Rechazo",
        "download csv": "Descargar CSV",
        "submitted": "Enviado:",
        "Phone Repair": "Reparación de Celulares",
        "Screen Replacement": "Cambio de Pantalla",
        "Battery Replacement": "Cambio de Batería",
        "Charging Port Repair": "Reparación de Puerto de Carga",
        "Water Damage Repair": "Reparación por Daño de Agua",
        "Software Troubleshooting": "Solución de Problemas de Software",
        "Data Recovery": "Recuperación de Datos",
        "job requests": "Trabajos",
        "Monday": "Lunes",
        "Tuesday": "Martes",
        "Wednesday": "Miércoles",
        "Thursday": "Jueves",
        "Friday": "Viernes",
        "Saturday": "Sábado",
        "Sunday": "Domingo",
        "Mon": "Lun",
        "Tue": "Mar",
        "Wed": "Mié",
        "Thu": "Jue",
        "Fri": "Vie",
        "Sat": "Sáb",
        "Sun": "Dom",

        // Service Categories
        "Handyman": "Ayudante General",
        "Electrician": "Electricista",
        "Plumber": "Plomero",
        "Painter": "Pintor",
        "Carpenter": "Carpintero",
        "Cleaner": "Limpieza",
        "Locksmith": "Cerrajero",
        "Gardener": "Jardinero",
        "Architect": "Arquitecto",
        "Mason": "Albañil",
        "Construction Worker": "Obrero de Construcción",
        "Welder": "Soldador",
        "Blacksmith": "Herrero",
        "Surveyor": "Topógrafo",
        "Housekeeper": "Ama de llaves",
        "Janitor": "Conserje",
        "Home Assistant": "Asistente del Hogar",
        "Launderer": "Lavandero",
        "Butler": "Mayordomo",
        "Cook": "Cocinero",
        "Waiter": "Mesero",
        "Taxi Driver": "Taxista",
        "Mechanic": "Mecánico",
        "Hairdresser": "Peluquero",
        "Baker": "Panadero",
        "Tailor": "Sastre",
        "Barber": "Barbero",
        "Mail Carrier": "Cartero",
        "Doctor": "Médico",
        "Nurse": "Enfermero",
        "Dentist": "Dentista",
        "Pharmacist": "Farmacéutico",
        "Pediatrician": "Pediatra",
        "Surgeon": "Cirujano",
        "Psychologist": "Psicólogo",
        "Physical Therapist": "Fisioterapeuta",
        "Nutritionist": "Nutricionista",
        "Teacher": "Profesor",
        "Primary School Teacher": "Maestro de Primaria",
        "Librarian": "Bibliotecario",
        "School Principal": "Director de Escuela",
        "Researcher": "Investigador",
        "Pedagogue": "Pedagogo",
        "School Counselor": "Orientador Escolar",
        "Accountant": "Contador",
        "Administrator": "Administrador",
        "Salesperson": "Vendedor",
        "Manager": "Gerente",
        "Economist": "Economista",
        "Financial Analyst": "Analista Financiero",
        "Stockbroker": "Corredor de Bolsa",
        "Treasurer": "Tesorero",
        "Web Developer": "Desarrollador Web",
        "Systems Technician": "Técnico de Sistemas",
        "Video Editor": "Editor de Video",
        "Photographer": "Fotógrafo",
        "Data Scientist": "Científico de Datos",
        "Programmer": "Programador",
        "Engineer": "Ingeniero",
        "Graphic Designer": "Diseñador Gráfico",
        "Journalist": "Periodista",
        "Lawyer": "Abogado",
        "Police Officer": "Oficial de Policía",
        "Judge": "Juez",
        "Prosecutor": "Fiscal",
        "Notary": "Notario",
        "Firefighter": "Bombero",
        "Security Guard": "Guardia de Seguridad",

        // Job Types
        "Furniture Assembly": "Montaje de Muebles",
        "TV Mounting": "Montaje de TV",
        "Minor Plumbing": "Plomería Menor",
        "Drywall Repair": "Reparación de Drywall",
        "Picture Hanging": "Colgar Cuadros",
        "General Repairs": "Reparaciones Generales",
        "Wiring & Rewiring": "Cableado y Recableado",
        "Fixture Installation": "Instalación de Lámparas",
        "Outlet & Switch Repair": "Reparación de Enchufes",
        "EV Charger Installation": "Instalación de Cargador VE",
        "Panel Upgrades": "Actualización de Panel",
        "Smart Home Setup": "Configuración de Hogar Inteligente",
        "Leak Repair": "Reparación de Fugas",
        "Drain Cleaning": "Limpieza de Desagües",
        "Toilet Installation": "Instalación de Inodoros",
        "Water Heater Repair": "Reparación de Calentador de Agua",
        "Pipe Fitting": "Instalación de Tuberías",
        "Garbage Disposal": "Triturador de Basura",
        "Interior Painting": "Pintura de Interiores",
        "Exterior Painting": "Pintura de Exteriores",
        "Cabinet Painting": "Pintura de Gabinetes",
        "Deck Staining": "Teñido de Terrazas",
        "Wallpaper Removal": "Remoción de Papel Tapiz",
        "Trim Painting": "Pintura de Molduras",
        "Custom Shelving": "Estanterías a Medida",
        "Trim & Molding": "Molduras y Acabados",
        "Deck Building": "Construcción de Terrazas",
        "Door Installation": "Instalación de Puertas",
        "Frame Repair": "Reparación de Marcos",
        "Cabinet Installation": "Instalación de Gabinetes",
        "Standard Cleaning": "Limpieza Estándar",
        "Deep Cleaning": "Limpieza Profunda",
        "Move-in/Move-out": "Limpieza de Mudanza",
        "Window Cleaning": "Limpieza de Ventanas",
        "Carpet Cleaning": "Limpieza de Alfombras",
        "Office Cleaning": "Limpieza de Oficinas",
        "Lockout Service": "Servicio de Cerrajería (Apertura)",
        "Lock Installation": "Instalación de Cerraduras",
        "Key Duplication": "Duplicado de Llaves",
        "Rekeying": "Cambio de Combinación",
        "Smart Lock Setup": "Instalación de Cerradura Inteligente",
        "Car Key Replacement": "Reemplazo de Llave de Auto",
        "Lawn Mowing": "Corte de Césped",
        "Weeding & Planting": "Desmalezado y Siembra",
        "Hedge Trimming": "Poda de Setos",
        "Garden Design": "Diseño de Jardines",
        "Tree Pruning": "Poda de Árboles",
        "Irrigation Systems": "Sistemas de Riego",
        "Residential Design": "Diseño Residencial",
        "Commercial Planning": "Planificación Comercial",
        "Blueprint Creation": "Creación de Planos",
        "Site Analysis": "Análisis de Sitio",
        "3D Modeling": "Modelado 3D",
        "Permit Applications": "Solicitud de Permisos",
        "Bricklaying": "Albañilería",
        "Concrete Work": "Trabajos de Hormigón",
        "Stone Masonry": "Mampostería de Piedra",
        "Chimney Repair": "Reparación de Chimeneas",
        "Foundation Work": "Trabajos de Cimentación",
        "Retaining Walls": "Muros de Contención",
        "Framing": "Estructuras",
        "Demolition": "Demolición",
        "Site Cleanup": "Limpieza de Obra",
        "General Labor": "Mano de Obra General",
        "Drywall Installation": "Instalación de Drywall",
        "Concrete Pouring": "Vaciado de Hormigón",
        "MIG Welding": "Soldadura MIG",
        "TIG Welding": "Soldadura TIG",
        "Stick Welding": "Soldadura por Electrodo",
        "Metal Fabrication": "Fabricación de Metales",
        "Pipe Welding": "Soldadura de Tuberías",
        "Structural Welding": "Soldadura Estructural",
        "Custom Ironwork": "Herrería a Medida",
        "Gate & Railing Fabrication": "Fabricación de Portones y Barandas",
        "Tool Forging": "Forja de Herramientas",
        "Metal Repair": "Reparación de Metales",
        "Decorative Pieces": "Piezas Decorativas",
        "Blade Smithing": "Forja de Cuchillos",
        "Land Surveying": "Levantamiento Topográfico",
        "Boundary Survey": "Deslinde de Terrenos",
        "Topographic Mapping": "Mapeo Topográfico",
        "Construction Staking": "Replanteo para Construcción",
        "ALTA/NSPS Surveys": "Levantamientos ALTA/NSPS",
        "Flood Elevation Certificates": "Certificados de Elevación de Inundación",
        "Tidying & Organizing": "Orden y Organización",
        "Bed Making": "Hacer Camas",
        "Dusting & Polishing": "Quitar Polvo y Pulir",
        "Vacuuming & Mopping": "Aspirar y Trapear",
        "Bathroom Cleaning": "Limpieza de Baños",
        "Kitchen Cleaning": "Limpieza de Cocina",
        "Commercial Office Cleaning": "Limpieza de Oficinas Comerciales",
        "Floor Buffing & Waxing": "Pulido y Encerado de Pisos",
        "Trash Removal": "Retiro de Basura",
        "Restroom Sanitization": "Sanitización de Baños",
        "Window Washing": "Lavado de Ventanas",
        "Event Cleanup": "Limpieza de Eventos",
        "Grocery Shopping": "Compras de Supermercado",
        "Errand Running": "Hacer Mandados",
        "Meal Preparation": "Preparación de Comidas",
        "Appointment Scheduling": "Agendar Citas",
        "Pet Care": "Cuidado de Mascotas",
        "Light Housekeeping": "Limpieza Ligera",
        "Wash & Fold Service": "Servicio de Lavado y Doblado",
        "Ironing & Pressing": "Planchado y Prensado",
        "Dry Cleaning Drop-off/Pickup": "Retiro/Entrega de Tintorería",
        "Stain Removal": "Quitamanchas",
        "Linen Service": "Servicio de Ropa de Cama",
        "Delicate Garment Care": "Cuidado de Ropa Delicada",
        "Event Serving & Management": "Servicio y Gestión de Eventos",
        "Wardrobe Management": "Gestión de Vestuario",
        "Household Staff Supervision": "Supervisión de Personal Doméstico",
        "Guest Reception & Valet": "Recepción de Invitados y Valet",
        "Travel Arrangements": "Arreglos de Viaje",
        "Personal Shopping": "Compras Personales",
        "Meal Prep": "Preparación de Comidas",
        "Event Catering": "Catering para Eventos",
        "Private Chef": "Chef Privado",
        "Specialty Cuisine": "Cocina de Especialidad",
        "Baking & Pastry": "Repostería y Pastelería",
        "Event Serving": "Servicio en Eventos",
        "Bartending": "Coctelería",
        "Restaurant Staffing": "Personal de Restaurante",
        "Fine Dining Service": "Servicio de Alta Cocina",
        "Banquets": "Banquetes",
        "Airport Transfer": "Traslado al Aeropuerto",
        "City Tours": "Tours por la Ciudad",
        "Corporate Transport": "Transporte Corporativo",
        "Package Delivery": "Entrega de Paquetes",
        "Local Rides": "Viajes Locales",
        "Oil Change": "Cambio de Aceite",
        "Brake Repair": "Reparación de Frenos",
        "Engine Diagnostics": "Diagnóstico de Motor",
        "Tire Rotation": "Rotación de Neumáticos",
        "General Maintenance": "Mantenimiento General",
        "Cut & Style": "Corte y Peinado",
        "Coloring": "Tinte",
        "Highlights": "Mechas",
        "Updos & Styling": "Recogidos y Peinados",
        "Hair Treatments": "Tratamientos Capilares",
        "Custom Cakes": "Pasteles Personalizados",
        "Wedding Cakes": "Pasteles de Boda",
        "Bread Baking": "Panadería",
        "Pastries & Desserts": "Repostería y Postres",
        "Artisan Breads": "Panes Artesanales",
        "Alterations": "Arreglos",
        "Custom Clothing": "Ropa a Medida",
        "Suit Fitting": "Ajuste de Trajes",
        "Dressmaking": "Confección de Vestidos",
        "Repairs & Mending": "Reparaciones y Zurcidos",
        "Classic Haircut": "Corte de Pelo Clásico",
        "Beard Trim": "Recorte de Barba",
        "Hot Towel Shave": "Afeitado con Toalla Caliente",
        "Fades & Tapers": "Desvanecidos y Tapers",
        "Head Shave": "Afeitado de Cabeza",
        "Local Package Delivery": "Entrega de Paquetes Locales",
        "Document Courier": "Mensajería de Documentos",
        "Bulk Mail Handling": "Manejo de Correo Masivo",
        "Scheduled Pickups": "Recogidas Programadas",
        "General Consultation": "Consulta General",
        "Annual Check-up": "Chequeo Anual",
        "Minor Illness Treatment": "Tratamiento de Enfermedades Menores",
        "Health Screening": "Evaluación de Salud",
        "Vaccinations": "Vacunación",
        "Home Care": "Cuidado a Domicilio",
        "Wound Dressing": "Curación de Heridas",
        "Medication Administration": "Administración de Medicamentos",
        "Post-operative Care": "Cuidado Postoperatorio",
        "Health Monitoring": "Monitoreo de Salud",
        "Dental Cleaning": "Limpieza Dental",
        "Fillings": "Empastes",
        "Check-up & X-Ray": "Revisión y Rayos X",
        "Tooth Extraction": "Extracción Dental",
        "Teeth Whitening": "Blanqueamiento Dental",
        "Prescription Filling": "Surtido de Recetas",
        "Medication Review": "Revisión de Medicamentos",
        "Health Advice": "Asesoramiento de Salud",
        "Over-the-counter Consultation": "Consulta de Medicamentos sin Receta",
        "Well-child Visits": "Visitas de Niño Sano",
        "Childhood Vaccinations": "Vacunas Infantiles",
        "Newborn Care": "Cuidado del Recién Nacido",
        "Sick Child Diagnosis": "Diagnóstico de Niño Enfermo",
        "Surgical Consultation": "Consulta Quirúrgica",
        "Minor Outpatient Procedures": "Procedimientos Menores Ambulatorios",
        "Post-Surgical Follow-up": "Seguimiento Postquirúrgico",
        "Individual Therapy": "Terapia Individual",
        "Couples Counseling": "Terapia de Pareja",
        "Family Therapy": "Terapia Familiar",
        "Psychological Assessment": "Evaluación Psicológica",
        "Injury Rehabilitation": "Rehabilitación de Lesiones",
        "Sports Therapy": "Terapia Deportiva",
        "Post-surgery Rehab": "Rehabilitación Postoperatoria",
        "Mobility Improvement": "Mejora de la Movilidad",
        "Diet Planning": "Planificación de Dietas",
        "Weight Management Counseling": "Asesoramiento para el Control de Peso",
        "Meal Prep Guidance": "Guía de Preparación de Comidas",
        "Nutritional Assessment": "Evaluación Nutricional",
        "Subject Tutoring (Math, Science, etc.)": "Tutoría de Materias (Mat, Cien, etc.)",
        "Language Lessons": "Clases de Idiomas",
        "Test Preparation (SAT, ACT)": "Preparación para Exámenes (SAT, ACT)",
        "Music Lessons": "Clases de Música",
        "College Application Help": "Ayuda con Solicitudes Universitarias",
        "Elementary Tutoring": "Tutoría de Primaria",
        "Reading & Writing Help": "Ayuda con Lectura y Escritura",
        "Homework Assistance": "Asistencia con Tareas",
        "Special Needs Support": "Apoyo a Necesidades Especiales",
        "Early Childhood Education": "Educación Infantil Temprana",
        "Research Assistance": "Asistencia en Investigación",
        "Cataloging Services": "Servicios de Catalogación",
        "Digital Archive Management": "Gestión de Archivos Digitales",
        "Story Time Sessions": "Sesiones de Cuentacuentos",
        "Information Literacy Workshops": "Talleres de Alfabetización Informacional",
        "Educational Consulting": "Consultoría Educativa",
        "School Administration Advice": "Asesoramiento en Administración Escolar",
        "Curriculum Development": "Desarrollo Curricular",
        "Teacher Training Workshops": "Talleres de Formación Docente",
        "Policy Review": "Revisión de Políticas",
        "Data Analysis": "Análisis de Datos",
        "Literature Review": "Revisión de Literatura",
        "Academic Writing": "Escritura Académica",
        "Survey Design": "Diseño de Encuestas",
        "Qualitative Research": "Investigación Cualitativa",
        "Learning Plan Development": "Desarrollo de Planes de Aprendizaje",
        "Educational Material Design": "Diseño de Material Educativo",
        "Child Development Assessment": "Evaluación del Desarrollo Infantil",
        "Parental Guidance": "Orientación para Padres",
        "Didactic Strategies": "Estrategias Didácticas",
        "Academic Advising": "Asesoramiento Académico",
        "Career Counseling": "Orientación Profesional",
        "College Guidance": "Orientación Universitaria",
        "Student Support Sessions": "Sesiones de Apoyo Estudiantil",
        "Social-Emotional Learning": "Aprendizaje Socioemocional",
        "Bookkeeping": "Contabilidad",
        "Tax Preparation": "Preparación de Impuestos",
        "Auditing": "Auditoría",
        "Financial Statements": "Estados Financieros",
        "Office Management": "Gestión de Oficina",
        "Data Entry": "Entrada de Datos",
        "Scheduling": "Programación",
        "Executive Assistance": "Asistencia Ejecutiva",
        "Retail Sales": "Ventas Minoristas",
        "B2B Sales": "Ventas B2B",
        "Lead Generation": "Generación de Leads",
        "Product Demonstration": "Demostración de Productos",
        "Project Management": "Gestión de Proyectos",
        "Team Leadership": "Liderazgo de Equipos",
        "Operations Management": "Gestión de Operaciones",
        "Strategic Planning": "Planificación Estratégica",
        "Economic Forecasting": "Previsión Económica",
        "Market Analysis": "Análisis de Mercado",
        "Policy Research": "Investigación de Políticas",
        "Financial Modeling": "Modelado Financiero",
        "Investment Analysis": "Análisis de Inversiones",
        "Portfolio Management": "Gestión de Carteras",
        "Financial Reporting": "Informes Financieros",
        "Risk Assessment": "Evaluación de Riesgos",
        "Stock Trading": "Negociación de Acciones",
        "Investment Advice": "Asesoramiento de Inversión",
        "Wealth Management": "Gestión de Patrimonios",
        "Market Orders": "Órdenes de Mercado",
        "Cash Management": "Gestión de Efectivo",
        "Corporate Finance": "Finanzas Corporativas",
        "Budgeting": "Presupuestos",
        "Financial Risk Management": "Gestión de Riesgos Financieros",
        "Frontend Development": "Desarrollo Frontend",
        "Backend Development": "Desarrollo Backend",
        "Full-Stack Development": "Desarrollo Full-Stack",
        "E-commerce Site": "Sitio de E-commerce",
        "CMS Setup": "Configuración de CMS",
        "IT Support": "Soporte TI",
        "Network Setup": "Configuración de Redes",
        "Hardware Repair": "Reparación de Hardware",
        "Server Maintenance": "Mantenimiento de Servidores",
        "Software Installation": "Instalación de Software",
        "Corporate Videos": "Videos Corporativos",
        "Social Media Content": "Contenido para Redes Sociales",
        "Wedding Videos": "Videos de Boda",
        "Short Films": "Cortometrajes",
        "Color Grading": "Corrección de Color",
        "Event Photography": "Fotografía de Eventos",
        "Portrait Photoshoot": "Sesión de Retratos",
        "Product Photography": "Fotografía de Productos",
        "Real Estate Photography": "Fotografía Inmobiliaria",
        "Wedding Photography": "Fotografía de Bodas",
        "Machine Learning Models": "Modelos de Machine Learning",
        "Data Visualization": "Visualización de Datos",
        "Predictive Analytics": "Análisis Predictivo",
        "Big Data Solutions": "Soluciones de Big Data",
        "Custom Software": "Software a Medida",
        "Mobile App Development": "Desarrollo de Apps Móviles",
        "Scripting & Automation": "Scripting y Automatización",
        "API Integration": "Integración de API",
        "Database Design": "Diseño de Bases de Datos",
        "Software Engineering": "Ingeniería de Software",
        "Civil Engineering Consultation": "Consulta de Ingeniería Civil",
        "Mechanical Design": "Diseño Mecánico",
        "Electrical Engineering": "Ingeniería Eléctrica",
        "Systems Engineering": "Ingeniería de Sistemas",
        "Logo Design": "Diseño de Logos",
        "Branding Package": "Paquete de Branding",
        "Marketing Materials": "Material de Marketing",
        "UI/UX Design": "Diseño UI/UX",
        "Social Media Graphics": "Gráficos para Redes Sociales",
        "Article Writing": "Redacción de Artículos",
        "Investigative Reporting": "Periodismo de Investigación",
        "Copywriting": "Redacción Publicitaria",
        "Interviewing": "Entrevistas",
        "Content Creation": "Creación de Contenido",
        "Legal Consultation": "Consulta Legal",
        "Contract Review": "Revisión de Contratos",
        "Family Law": "Derecho Familiar",
        "Criminal Defense": "Defensa Penal",
        "Private Security": "Seguridad Privada",
        "Event Security": "Seguridad de Eventos",
        "Security Consulting": "Consultoría de Seguridad",
        "Legal Mediation": "Mediación Legal",
        "Arbitration Services": "Servicios de Arbitraje",
        "Case Review": "Revisión de Casos",
        "Document Notarization": "Notarización de Documentos",
        "Apostille Services": "Servicios de Apostilla",
        "Loan Signing Agent": "Agente de Firmas de Préstamos",
        "Mobile Notary": "Notario a Domicilio",
        "Fire Safety Inspection": "Inspección de Seguridad contra Incendios",
        "First Aid Training": "Capacitación en Primeros Auxilios",
        "Event Standby": "Servicio de Emergencia en Eventos",
        "Personal Bodyguard": "Guardaespaldas Personal",
        "Property Surveillance": "Vigilancia de Propiedades",
        "Mobile Patrol": "Patrullaje Móvil",
        "secure payment": "Pago Seguro",
        "you are paying a total of": "Estás pagando un total de",
        "name on card": "Nombre en la Tarjeta",
        "card number": "Número de Tarjeta",
        "expiry date": "Fecha de Expiración",
        "cvc": "CVC",
        "please fill in all card details": "Por favor, completa todos los detalles de la tarjeta.",
        "please enter a valid 16-digit card number": "Por favor, introduce un número de tarjeta válido de 16 dígitos.",
        "please use mm/yy format for expiry date": "Por favor, usa el formato MM/AA para la fecha de expiración.",
        "please enter a valid cvc": "Por favor, introduce un CVC válido.",
        "pay": "Pagar",
        "payment successful": "Pago Exitoso",
        "a receipt for your transaction": "Un recibo de tu transacción",
        "paid by": "Pagado por",
        "paid to": "Pagado a",
        "summary": "Resumen",
        "total paid": "Total Pagado",
        "close": "Cerrar",
        "all items must have a description and an amount greater than zero": "Todos los artículos deben tener una descripción y un monto mayor a cero.",
        "you must add at least one item to the invoice": "Debes añadir al menos un artículo a la factura.",
        "item description placeholder": "Descripción del Artículo (ej. Mano de obra, Materiales)",
        "amount": "Monto",
        "please provide a final resolution summary": "Por favor, proporciona un resumen final de la resolución.",
        "partial refund must be greater than 0 and less than total": "El reembolso parcial debe ser mayor a $0 y menor al total de {total}.",
        "please complete all verification steps": "Por favor, completa todos los pasos de verificación.",
        "please provide a reason for declining": "Por favor, proporciona una razón para rechazar.",
        "please select a date time and provide a description": "Por favor, selecciona una fecha, hora y proporciona una descripción.",
        "your tufix recovery code is": "Tu código de recuperación de TUFIX es: {code}",
        "account has been approved": "La cuenta de {name} ha sido aprobada.",
        "account has been declined": "La cuenta de {name} ha sido rechazada.",
        "please log in as a user to book a service": "Por favor, inicia sesión como usuario para reservar un servicio.",
        "booking request submitted successfully": "¡Solicitud de reserva enviada con éxito!",
        "cannot release payment while dispute is active": "No se puede liberar el pago mientras haya una disputa activa. Por favor, espera a que un administrador resuelva la disputa.",
        "error invoice is not in a payable state": "Error: La factura no está en un estado pagable.",
        "job confirmed and payment released": "¡Trabajo confirmado y pago liberado! El proveedor de servicios ha sido pagado.",
        "profile updated successfully": "¡Perfil actualizado con éxito!",
        "invoice sent you can now start the job": "¡Factura enviada! Ahora puedes comenzar el trabajo.",
        "payment successful funds held securely": "¡Pago exitoso! Los fondos se retienen de forma segura hasta que apruebes el pago.",
        "error could not find all related records for this dispute": "Error: No se pudieron encontrar todos los registros relacionados para esta disputa.",
        "dispute has been resolved and funds have been processed": "La disputa ha sido resuelta y los fondos han sido procesados.",
        "terms and services updated successfully": "¡Términos y Servicios actualizados con éxito!",
        "you have been connected to a live support agent": "Has sido conectado con un agente de soporte en vivo. Puedes encontrar el chat en tus mensajes.",
        "admin accounts cannot be created": "Las cuentas de administrador no se pueden crear desde el formulario de registro.",
        "service provider": "Proveedor de Servicios",
        "administrator": "Administrador",
        "find the perfect professional": "Encuentra al profesional perfecto",
        "grow your business": "Haz crecer tu negocio",
        "manage the platform": "Gestiona la plataforma",
        "connect with skilled workers": "Conéctate con trabajadores calificados en tu área para cualquier trabajo.",
        "find clients and manage jobs": "Encuentra clientes y gestiona tus trabajos en un solo lugar.",
        "oversee users workers and platform": "Supervisa usuarios, trabajadores y la actividad de la plataforma.",
        "ai support welcome": "¡Hola! Soy tu asistente de IA de TUFIX. ¿Cómo puedo ayudarte a entender nuestra plataforma?",
        "ai support error": "Lo siento, algo salió mal. Por favor, inténtalo de nuevo.",
        "tufix ai support": "Soporte de IA de TUFIX",
        "ask placeholder": "Preguntar...",
        "language": "Idioma",
        "close ai support chat": "Cerrar chat de soporte de IA",
        "open ai support chat": "Abrir chat de soporte de IA",
        "all items must have description and amount": "Todos los artículos deben tener una descripción y un monto válido mayor a cero.",
        "must add at least one item": "Debes agregar al menos un artículo a la factura.",
        "for client": "Para:",
        "item description example": "Descripción del artículo (ej. Mano de obra)",
        "total": "Total:",
        "send invoice": "Enviar Factura",
        "recovery code sent": "Se te ha enviado un código de recuperación. Por favor, ingrésalo a continuación.",
        "edit your profile": "Edita tu perfil",
        "change photo": "Cambiar foto",
        "full name": "Nombre completo",
        "location": "Ubicación",
        "about me bio": "Sobre mí (Biografía)",
        "weekly availability": "Disponibilidad semanal",
        "start_time": "Desde",
        "end_time": "Hasta",
        "save changes": "Guardar cambios",
        "new status": "Nuevo",
        "accepted status": "Aceptado",
        "completed status": "Completado",
        "disputed status": "En disputa",
        "no specific services listed": "No hay servicios específicos listados en esta categoría todavía.",
        "invoice not found": "Factura no encontrada.",
        "in conversation with": "En conversación con {name}",
        "image selected ready to send": "Imagen seleccionada. Lista para enviar.",
        "send image": "Enviar Imagen",
        "english": "Inglés (EN)",
        "spanish": "Español (ES)",
        "regular": "Regular",
        "custom": "Personalizado",
        "day off": "Día Libre",
        "available": "Disponible",
        "unavailable": "No Disponible",
        "no worker data": "No hay datos de proveedores.",
        "price not available": "Precio no disponible",
        "no reviews yet": "Este profesional no tiene reseñas todavía.",
        "supported formats": "JPG, PNG o PDF",
        "camera access error": "No se pudo acceder a la cámara. Por favor, comprueba los permisos e inténtalo de nuevo.",
        "failed to send verification code": "Error al enviar el código de verificación",
        "sms error": "No se pudo enviar el SMS: {error}. Por favor, comprueba tu configuración de Twilio.",
        "invalid verification code": "Código de verificación inválido. Por favor, inténtalo de nuevo.",
        "danger zone": "Zona de Peligro",
        "clear all data description": "Esto eliminará permanentemente todos los usuarios, trabajadores, trabajos, mensajes y notificaciones de la base de datos. Esta acción no se puede deshacer.",
        "clear all data": "Borrar Todos los Datos",
        "confirm clear all data": "Confirmar Borrado de Datos",
        "clear all data warning": "¿Estás seguro de que quieres eliminar todo? Esto reiniciará toda la base de datos de la aplicación.",
        "yes clear all": "Sí, Borrar Todo",
        "worker verification": "Verificación de Trabajador",
        "worker verification description": "Revise los documentos presentados para aprobar o rechazar al nuevo proveedor de servicios.",
        "provider details": "Detalles del Proveedor",
        "id document": "Documento de Identidad",
        "no id photo submitted": "No se ha enviado foto de la identificación.",
        "selfie": "Selfie",
        "no selfie submitted": "No se ha enviado selfie.",
        "decline application": "Rechazar Solicitud",
        "decline application description": "Proporcione un motivo claro para rechazar esta solicitud. Este motivo se compartirá con el solicitante.",
        "decline reason placeholder": "ej., la foto de la identificación no es clara, la selfie no coincide con la identificación...",
        "id prefix": "ID:",
        "fee prefix": "Comisión:",
        "held": "Retenido",
        "released": "Liberado",
        "not available": "No disponible",
        "verify_phone_description": "Por favor verifique su número de teléfono, le hemos enviado un código de 4 dígitos a",
        "not_found": "No encontrado",
        "january": "Enero",
        "february": "Febrero",
        "march": "Marzo",
        "april": "Abril",
        "may": "Mayo",
        "june": "Junio",
        "july": "Julio",
        "august": "Agosto",
        "september": "Septiembre",
        "october": "Octubre",
        "november": "Noviembre",
        "december": "Diciembre",
        "monday": "Lunes",
        "tuesday": "Martes",
        "wednesday": "Miércoles",
        "thursday": "Jueves",
        "friday": "Viernes",
        "saturday": "Sábado",
        "sunday": "Domingo",
        "newly registered service provider": "Trabajador nuevo en la plataforma.",
        "general menu": "Menú general",
        "sun": "Dom",
        "mon": "Lun",
        "tue": "Mar",
        "wed": "Mié",
        "thu": "Jue",
        "fri": "Vie",
        "sat": "Sáb",
        "messages": "Mensajes",
        "profile": "Perfil",
        "earnings": "Ganancias",
        "notifications": "Notificaciones"
    }
};


export const useTranslations = () => {
    const [language, setLanguage] = useLocalStorage<Language>('language', 'es');

    const t = useCallback(
        (key: string, replacements?: Record<string, string | number>): string => {
            const langTranslations = translations[language] || translations.en;
            let translation = langTranslations[key] || translations.en[key] || key;

            if (replacements) {
                Object.keys(replacements).forEach((rKey) => {
                    translation = translation.replace(
                        new RegExp(`\\{${rKey}\\}`, 'g'),
                        String(replacements[rKey])
                    );
                });
            }
            return translation;
        },
        [language]
    );

    return { language, setLanguage, t };
};